// AUTO-GENERATED by scripts/probes/recalibrate-base-curve.ts
// DO NOT EDIT MANUALLY. Re-run the harness against the H10 corpus to
// regenerate.
//
// Per-Amazon-root-category multipliers applied on top of the v1.2.0
// base BSR curve. Trained against ~3,000 unique ASINs from the merged
// corpus (H10 Xray CSV exports + single-variation submissions).
//
// Each multiplier represents median(observedH10ParentSales / v12CurveOutput)
// for that category — a value < 1.0 means the universal curve
// overestimates units in this category; > 1.0 means it underestimates.
//
// Categories with median ratio outside 0.5x-2.0x are intentionally
// omitted (they fall back to 1.0x = base curve). Today that means:
// Home & Kitchen, Health & Household, Clothing/Shoes/Jewelry — all
// three have extreme medians (3-5x) that almost certainly reflect
// sub-category-mix issues, not a single-multiplier-fix problem. Phase
// 5.4-I will address with sub-category granularity.
//
// Calibration date: 2026-05-04

export const CATEGORY_CALIBRATION_VERSION = 'v3-2026-05-04';

export const CATEGORY_MULTIPLIERS: Record<string, number> = {
  "Kitchen & Dining": 0.853,            // n=488
  "Sports & Outdoors": 0.758,           // n=280
  "Pet Supplies": 0.611,                // n=217
  "Toys & Games": 1.199,                // n=202
  "Office Products": 1.288,             // n=172
  "Patio, Lawn & Garden": 0.635,        // n=166
  "Tools & Home Improvement": 1.614,    // n=164
  "Baby": 0.925,                        // n=115
  "Baby Products": 0.925,               // alias — Keepa returns "Baby Products" for the same root
  "Arts, Crafts & Sewing": 0.579,       // n=104
  "Electronics": 0.624,                 // n=92
  "Industrial & Scientific": 0.523,     // n=70
};

/**
 * Look up a category multiplier. Returns 1.0 (no-op) for categories
 * we haven't calibrated — keeps the base curve as the safe fallback
 * rather than guessing.
 */
export function categoryMultiplier(category: string | null | undefined): number {
  if (!category) return 1;
  return CATEGORY_MULTIPLIERS[category] ?? 1;
}
