import jsPDF from 'jspdf';
import type { SupplierQuoteRow } from '../../types';
import { formatCurrency } from '@/utils/formatters';

interface ChecklistItem {
  id: string;
  label: string;
  value: string | null;
  required: boolean;
  section: string;
}

interface GeneratePDFParams {
  productId: string;
  productName: string;
  supplier: SupplierQuoteRow;
  supplierWithMetrics: SupplierQuoteRow;
  checklistItems: ChecklistItem[];
  confirmedItems: Set<string>;
  orderQuantity: number;
  tier: 'short' | 'medium' | 'long';
  targetSalesPrice: number | null;
  referralFeePct: number | null;
  inspectionNotes: string;
}

// Brand palette (BloomEngine purple/indigo)
const BRAND = {
  primary: [109, 40, 217] as [number, number, number],         // purple-700
  primaryLight: [196, 181, 253] as [number, number, number],   // purple-300
  accent: [79, 70, 229] as [number, number, number],           // indigo-600
  text: [15, 23, 42] as [number, number, number],              // slate-900
  textMuted: [71, 85, 105] as [number, number, number],        // slate-600
  textLight: [148, 163, 184] as [number, number, number],      // slate-400
  rule: [226, 232, 240] as [number, number, number],           // slate-200
  bgSoft: [248, 250, 252] as [number, number, number],         // slate-50
  bgEmerald: [236, 253, 245] as [number, number, number],      // emerald-50
  emerald: [4, 120, 87] as [number, number, number],           // emerald-700
};

export function generatePurchaseOrderPDF(params: GeneratePDFParams) {
  const {
    productId,
    productName,
    supplier,
    supplierWithMetrics,
    confirmedItems,
    orderQuantity,
    tier,
    inspectionNotes,
  } = params;

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;

  // ---------- Helpers ----------
  const setColor = (rgb: [number, number, number]) => doc.setTextColor(rgb[0], rgb[1], rgb[2]);
  const setFill = (rgb: [number, number, number]) => doc.setFillColor(rgb[0], rgb[1], rgb[2]);
  const setStroke = (rgb: [number, number, number]) => doc.setDrawColor(rgb[0], rgb[1], rgb[2]);

  const ensureSpace = (needed: number) => {
    if (y + needed > pageHeight - margin) {
      drawFooter();
      doc.addPage();
      y = margin;
    }
  };

  const sectionHeader = (title: string) => {
    ensureSpace(14);
    y += 4;
    setFill(BRAND.bgSoft);
    doc.rect(margin, y, contentWidth, 8, 'F');
    setStroke(BRAND.primary);
    doc.setLineWidth(0.6);
    doc.line(margin, y, margin + 3, y);
    doc.line(margin, y, margin, y + 8);
    doc.setLineWidth(0.2);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    setColor(BRAND.primary);
    doc.text(title.toUpperCase(), margin + 4, y + 5.5);
    y += 11;
  };

  const kvRow = (label: string, value: string, opts: { bold?: boolean; emphasis?: boolean } = {}) => {
    ensureSpace(6);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    setColor(BRAND.textMuted);
    doc.text(label, margin + 2, y);
    doc.setFont('helvetica', opts.bold || opts.emphasis ? 'bold' : 'normal');
    doc.setFontSize(opts.emphasis ? 10 : 9);
    setColor(opts.emphasis ? BRAND.emerald : BRAND.text);
    doc.text(value || '—', margin + 60, y);
    y += 5.5;
  };

  const drawFooter = () => {
    const fy = pageHeight - 10;
    setColor(BRAND.textLight);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.text(`Generated by BloomEngine · ${new Date().toLocaleString()}`, margin, fy);
    doc.text(
      `Page ${doc.getCurrentPageInfo().pageNumber}`,
      pageWidth - margin,
      fy,
      { align: 'right' }
    );
  };

  const drawTwoColBlock = (
    leftTitle: string,
    leftLines: string[],
    rightTitle: string,
    rightLines: string[]
  ) => {
    const colWidth = (contentWidth - 4) / 2;
    const blockHeight = Math.max(leftLines.length, rightLines.length) * 5 + 14;
    ensureSpace(blockHeight + 4);

    const startY = y;

    [
      { x: margin, title: leftTitle, lines: leftLines },
      { x: margin + colWidth + 4, title: rightTitle, lines: rightLines },
    ].forEach(({ x, title, lines }) => {
      setStroke(BRAND.rule);
      doc.setLineWidth(0.3);
      doc.rect(x, startY, colWidth, blockHeight);

      setFill(BRAND.primary);
      doc.rect(x, startY, colWidth, 6, 'F');
      setColor([255, 255, 255]);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text(title.toUpperCase(), x + 3, startY + 4.2);

      setColor(BRAND.text);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      lines.forEach((line, i) => {
        doc.text(line || '—', x + 3, startY + 11 + i * 5);
      });
    });

    y = startY + blockHeight + 6;
  };

  // ---------- 1. Brand header ----------
  setFill(BRAND.primary);
  doc.rect(0, 0, pageWidth, 26, 'F');
  setColor([255, 255, 255]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('BloomEngine', margin, 14);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text('Sourcing · Purchase Order', margin, 19);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('PURCHASE ORDER', pageWidth - margin, 14, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const poNumber = `PO-${productId}-${new Date().toISOString().slice(0, 10).replace(/-/g, '')}`;
  doc.text(poNumber, pageWidth - margin, 20, { align: 'right' });

  y = 36;

  // ---------- 2. PO meta strip ----------
  setColor(BRAND.textMuted);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Issue date', margin, y);
  doc.text('Tier', margin + 60, y);
  doc.text('Quantity', margin + 110, y);

  y += 5;
  setColor(BRAND.text);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text(new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }), margin, y);
  const tierLabel = tier === 'medium' ? 'Medium-term' : tier === 'long' ? 'Long-term' : 'Short-term';
  doc.text(tierLabel, margin + 60, y);
  doc.text(`${orderQuantity.toLocaleString()} units`, margin + 110, y);
  y += 8;

  // ---------- 3. Buyer / Supplier two-col block ----------
  const place = supplier.placeOrderFields || {};
  const buyerLines = [
    place.yourName || '',
    place.companyName || place.brandName || '',
    place.companyAddress || '',
    place.companyPhoneNumber || '',
  ].filter(Boolean);
  if (buyerLines.length === 0) buyerLines.push('—');

  const supplierLines = [
    supplier.displayName || supplier.supplierName || '',
    supplier.companyName || '',
    supplier.supplierAddress || '',
    supplier.supplierContactNumber || '',
    supplier.supplierEmail || '',
  ].filter(Boolean);
  if (supplierLines.length === 0) supplierLines.push('—');

  drawTwoColBlock('Buyer', buyerLines, 'Supplier', supplierLines);

  // ---------- 4. Product ----------
  sectionHeader('Product');
  kvRow('Product Name', productName || '—');
  kvRow('ASIN', productId);
  if (place.productSku) kvRow('SKU', place.productSku);
  if (place.productSize) kvRow('Size', place.productSize);
  if (place.color) kvRow('Color', place.color);
  if (place.materialUsed) kvRow('Material', place.materialUsed);
  if (place.upcFnsku) kvRow('UPC / FNSKU', place.upcFnsku);
  y += 2;

  // ---------- 5. Order Summary (highlighted) ----------
  ensureSpace(48);
  sectionHeader('Order Summary');

  // Compute money stats
  let costPerUnit: number | null = null;
  const effectiveIncoterms = supplier.incotermsAgreed || supplier.incoterms || 'DDP';
  if (tier === 'medium' && supplier.costPerUnitMediumTerm != null) {
    costPerUnit = supplier.costPerUnitMediumTerm;
  } else if (tier === 'long' && supplier.costPerUnitLongTerm != null) {
    costPerUnit = supplier.costPerUnitLongTerm;
  } else {
    costPerUnit = supplier.costPerUnitShortTerm ?? supplier.exwUnitCost ?? null;
  }
  const proFormaTotal = costPerUnit != null ? orderQuantity * costPerUnit : null;

  // Highlight box for the four money stats
  const summaryBoxY = y;
  const summaryHeight = 28;
  setFill(BRAND.bgEmerald);
  doc.rect(margin, summaryBoxY, contentWidth, summaryHeight, 'F');
  setStroke(BRAND.emerald);
  doc.setLineWidth(0.4);
  doc.rect(margin, summaryBoxY, contentWidth, summaryHeight);

  const cellWidth = contentWidth / 4;
  const moneyStats: Array<[string, string]> = [
    ['Final MOQ', orderQuantity.toLocaleString()],
    ['Cost / Unit', costPerUnit != null ? formatCurrency(costPerUnit) : '—'],
    ['Pro Forma Total', proFormaTotal != null ? formatCurrency(proFormaTotal) : '—'],
    [
      'Profit / Unit',
      supplierWithMetrics.profitPerUnit != null ? formatCurrency(supplierWithMetrics.profitPerUnit) : '—',
    ],
  ];

  moneyStats.forEach(([label, value], i) => {
    const cellX = margin + i * cellWidth;
    setColor(BRAND.textMuted);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.text(label.toUpperCase(), cellX + 4, summaryBoxY + 7);
    setColor(BRAND.emerald);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text(value, cellX + 4, summaryBoxY + 18);
  });

  // Margin / ROI as smaller stat row below
  y = summaryBoxY + summaryHeight + 4;
  setColor(BRAND.textMuted);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  const marginText =
    supplierWithMetrics.marginPct != null ? `${supplierWithMetrics.marginPct.toFixed(1)}%` : '—';
  const roiText = supplierWithMetrics.roiPct != null ? `${supplierWithMetrics.roiPct.toFixed(1)}%` : '—';
  doc.text(`Margin: ${marginText}    ·    ROI: ${roiText}`, margin + 2, y);
  y += 6;

  // ---------- 6. Terms ----------
  sectionHeader('Order Terms');
  kvRow('Incoterms', effectiveIncoterms);
  kvRow('Lead Time', supplier.leadTime || '—');
  kvRow('Payment Terms', supplier.paymentTerms || '—');
  if (place.freightForwarder) kvRow('Freight Forwarder', place.freightForwarder);
  if (place.shippingTime) kvRow('Shipping Time', place.shippingTime);
  if (place.htsCode) kvRow('HTS Code', place.htsCode);
  y += 2;

  // ---------- 7. Product specifications ----------
  sectionHeader('Product Specifications');
  if (
    supplier.singleProductPackageLengthCm != null &&
    supplier.singleProductPackageWidthCm != null &&
    supplier.singleProductPackageHeightCm != null
  ) {
    kvRow(
      'Unit Package',
      `${supplier.singleProductPackageLengthCm} × ${supplier.singleProductPackageWidthCm} × ${supplier.singleProductPackageHeightCm} cm`
    );
  }
  if (supplier.singleProductPackageWeightKg != null) {
    kvRow('Unit Weight', `${supplier.singleProductPackageWeightKg} kg`);
  }
  if (
    supplier.cartonLengthCm != null &&
    supplier.cartonWidthCm != null &&
    supplier.cartonHeightCm != null
  ) {
    kvRow(
      'Carton Dimensions',
      `${supplier.cartonLengthCm} × ${supplier.cartonWidthCm} × ${supplier.cartonHeightCm} cm`
    );
  }
  if (supplier.cartonWeightKg != null) kvRow('Carton Weight', `${supplier.cartonWeightKg} kg`);
  if (supplier.unitsPerCarton != null) kvRow('Units / Carton', supplier.unitsPerCarton.toLocaleString());
  if (supplier.cbmPerCarton != null) kvRow('CBM / Carton', `${supplier.cbmPerCarton.toFixed(3)} m³`);
  if (supplier.totalCbm != null) kvRow('Total CBM', `${supplier.totalCbm.toFixed(2)} m³`);
  y += 2;

  // ---------- 8. Cost breakdown ----------
  sectionHeader('Cost Breakdown (per unit)');
  if (supplier.sspCostPerUnit != null) kvRow('SSP Cost', formatCurrency(supplier.sspCostPerUnit));
  if (supplier.labellingCostPerUnit != null) kvRow('Labelling', formatCurrency(supplier.labellingCostPerUnit));
  if (supplier.packagingCostPerUnit != null) kvRow('Packaging', formatCurrency(supplier.packagingCostPerUnit));
  if (supplier.inspectionCostPerUnit != null) kvRow('Inspection', formatCurrency(supplier.inspectionCostPerUnit));
  if (supplier.freightCostPerUnit != null) kvRow('Freight', formatCurrency(supplier.freightCostPerUnit));
  if (supplier.dutyCostPerUnit != null) kvRow('Duty', formatCurrency(supplier.dutyCostPerUnit));
  if (supplier.tariffCostPerUnit != null) kvRow('Tariff', formatCurrency(supplier.tariffCostPerUnit));
  if (supplier.fbaFeePerUnit != null) kvRow('FBA Fee', formatCurrency(supplier.fbaFeePerUnit));
  y += 2;

  // ---------- 9. Super Selling Points ----------
  if (supplier.ssps && supplier.ssps.length > 0) {
    sectionHeader('Super Selling Points');
    setColor(BRAND.text);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    supplier.ssps
      .filter((s) => s.description?.trim())
      .forEach((s) => {
        ensureSpace(8);
        doc.setFont('helvetica', 'bold');
        doc.text('•', margin + 2, y);
        doc.setFont('helvetica', 'bold');
        doc.text(s.type, margin + 6, y);
        doc.setFont('helvetica', 'normal');
        const wrapped = doc.splitTextToSize(s.description, contentWidth - 38);
        doc.text(wrapped, margin + 38, y);
        y += Math.max(5, wrapped.length * 5);
        y += 1;
      });
    y += 2;
  }

  // ---------- 10. Sampling & quality ----------
  const hasSamplingData =
    supplier.sampleOrdered != null ||
    supplier.sampleQualityScore != null ||
    supplier.sampleRefundUponOrder != null;
  if (hasSamplingData) {
    sectionHeader('Sampling & Quality');
    if (supplier.sampleOrdered != null) {
      const so =
        typeof supplier.sampleOrdered === 'boolean'
          ? supplier.sampleOrdered
            ? 'Yes'
            : 'No'
          : supplier.sampleOrdered;
      kvRow('Sample Ordered', String(so));
    }
    if (supplier.sampleQualityScore != null) {
      kvRow('Sample Quality', `${supplier.sampleQualityScore} / 10`);
    }
    if (supplier.sampleRefundUponOrder != null) {
      kvRow('Refund Upon Order', supplier.sampleRefundUponOrder ? 'Yes' : 'No');
    }
    if (supplier.sampleNotes) {
      ensureSpace(8);
      setColor(BRAND.textMuted);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.text('Notes', margin + 2, y);
      setColor(BRAND.text);
      const wrapped = doc.splitTextToSize(supplier.sampleNotes, contentWidth - 60);
      doc.text(wrapped, margin + 60, y);
      y += Math.max(5, wrapped.length * 5);
    }
    y += 2;
  }

  // ---------- 11. Supplier grading ----------
  const hasGrading =
    supplier.opennessToSsps ||
    supplier.communication ||
    supplier.sellsOnAmazon ||
    supplier.sampling ||
    supplier.alibabaTradeAssurance ||
    supplier.supplierGrade;
  if (hasGrading) {
    sectionHeader('Supplier Grading');
    if (supplier.supplierGrade) kvRow('Overall Grade', supplier.supplierGrade, { emphasis: true });
    if (supplier.opennessToSsps) kvRow('Openness to SSPs', supplier.opennessToSsps);
    if (supplier.communication) kvRow('Communication', supplier.communication);
    if (supplier.sellsOnAmazon) kvRow('Sells on Amazon', supplier.sellsOnAmazon);
    if (supplier.sampling) kvRow('Sampling', supplier.sampling);
    if (supplier.alibabaTradeAssurance) kvRow('Alibaba Trade Assurance', supplier.alibabaTradeAssurance);
    y += 2;
  }

  // ---------- 12. Inspection notes ----------
  if (inspectionNotes?.trim()) {
    sectionHeader('Inspection Notes');
    setColor(BRAND.text);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    const wrapped = doc.splitTextToSize(inspectionNotes, contentWidth - 4);
    ensureSpace(wrapped.length * 5 + 4);
    doc.text(wrapped, margin + 2, y);
    y += wrapped.length * 5 + 2;
  }
  if (place.additionalNotesForSupplier?.trim()) {
    sectionHeader('Additional Notes for Supplier');
    setColor(BRAND.text);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    const wrapped = doc.splitTextToSize(place.additionalNotesForSupplier, contentWidth - 4);
    ensureSpace(wrapped.length * 5 + 4);
    doc.text(wrapped, margin + 2, y);
    y += wrapped.length * 5 + 2;
  }

  // ---------- 13. Confirmed checklist count ----------
  ensureSpace(10);
  y += 4;
  setColor(BRAND.textMuted);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text(
    `${confirmedItems.size} checklist item${confirmedItems.size === 1 ? '' : 's'} confirmed by buyer in BloomEngine`,
    margin,
    y
  );
  y += 6;

  // ---------- 14. Signature block ----------
  ensureSpace(40);
  y += 8;
  const colWidth = (contentWidth - 8) / 2;

  [
    { x: margin, label: 'Buyer Signature', name: place.yourName },
    { x: margin + colWidth + 8, label: 'Supplier Signature', name: supplier.supplierName || supplier.displayName },
  ].forEach(({ x, label, name }) => {
    setStroke(BRAND.text);
    doc.setLineWidth(0.3);
    doc.line(x, y + 14, x + colWidth, y + 14);
    setColor(BRAND.textMuted);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(label, x, y + 18);
    if (name) {
      setColor(BRAND.textLight);
      doc.text(name, x + colWidth, y + 18, { align: 'right' });
    }

    doc.line(x, y + 28, x + colWidth, y + 28);
    setColor(BRAND.textMuted);
    doc.text('Date', x, y + 32);
  });

  // Footer on the last page
  drawFooter();

  // ---------- Save ----------
  const supplierName = supplier.displayName || supplier.supplierName || 'Supplier';
  const sanitized = supplierName.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  const filename = `PO_${sanitized}_${productId}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
